export {default as FoodDetail} from './FoodDetail';
export {default as Home} from './Home';
export {default as Order} from './Order';
export {default as Profile} from './Profile';
export {default as SignIn} from './SignIn';
export {default as SignUp} from './SignUp';
export {default as SignUpAddress} from './SignUpAddress';
export {default as SplashScreen} from './SplashScreen';
export {default as SuccessSignUp} from './SuccessSignUp';
